[tools]
"aqua:hashicorp/terraform-plugin-docs" = "0.25.0"
go = "1.26.3"
opentofu = "1.12.1"
prek = "0.3.2"
terraform = "1.14.9"

[tasks.test]
description = "Run acceptance tests against the local dev server"
run = "TF_ACC=1 go test -count=1 ./internal/provider/... -v -timeout 120s"
env = { _.file = ".env" }

[tasks.docs]
description = "Generate documentations"
run = "tfplugindocs"
